type: models.nif.MAPIF_SDF

mapif:
  spec: # need this to stop utils.object parse
    type: models.mlp.MLP
    out_dim: 1
    hidden_list: [256, 256, 256, 256]

sdfnet:
  spec: # need this to stop utils.object parse
    type: models.mlp.MLP
    out_dim: 1
    hidden_list: [256, 256, 256, 256]


defaults:
  - edsr_baseline@encoder